bp_blog_homepage:
    path:     /blog/index
    defaults: { _controller: BPBlogBundle:Blog:index }

bp_blog_porfolio:
    path:     /blog/porfolio
    defaults: { _controller: BPBlogBundle:Blog:porfolio }

bp_blog_blog:
    path:     /blog/blog
    defaults: { _controller: BPBlogBundle:Blog:blog }

bp_blog_article1:
    path:     /blog/blog/1
    defaults: { _controller: BPBlogBundle:Blog:articleOne}
bp_blog_article2:
    path:     /blog/blog/2
    defaults: { _controller: BPBlogBundle:Blog:articleTwo}
bp_blog_article3:
    path:     /blog/blog/3
    defaults: { _controller: BPBlogBundle:Blog:articleThree}
bp_blog_contact:
    path:     /blog/contact
    defaults: { _controller: BPBlogBundle:Blog:contact }